INSERT INTO `SEX` (`SEX_CD`, `SEX_DESC`, `SEX_TERMNT_DT`, `LAST_UD_DT`, `LAST_UD_USER_ID`) VALUES ("1","Male      ",NULL,"03/20/02 00:00:00","CONVERT ");
INSERT INTO `SEX` (`SEX_CD`, `SEX_DESC`, `SEX_TERMNT_DT`, `LAST_UD_DT`, `LAST_UD_USER_ID`) VALUES ("2","Female    ",NULL,"03/20/02 00:00:00","CONVERT ");
INSERT INTO `SEX` (`SEX_CD`, `SEX_DESC`, `SEX_TERMNT_DT`, `LAST_UD_DT`, `LAST_UD_USER_ID`) VALUES ("9","Unknown   ",NULL,"03/20/02 00:00:00","CONVERT ");
