INSERT INTO `WKDAY` (`WKDAY_CD`, `WKDAY_SHORT_DESC`) VALUES ("1","Sun");
INSERT INTO `WKDAY` (`WKDAY_CD`, `WKDAY_SHORT_DESC`) VALUES ("2","Mon");
INSERT INTO `WKDAY` (`WKDAY_CD`, `WKDAY_SHORT_DESC`) VALUES ("3","Tue");
INSERT INTO `WKDAY` (`WKDAY_CD`, `WKDAY_SHORT_DESC`) VALUES ("4","Wed");
INSERT INTO `WKDAY` (`WKDAY_CD`, `WKDAY_SHORT_DESC`) VALUES ("5","Thu");
INSERT INTO `WKDAY` (`WKDAY_CD`, `WKDAY_SHORT_DESC`) VALUES ("6","Fri");
INSERT INTO `WKDAY` (`WKDAY_CD`, `WKDAY_SHORT_DESC`) VALUES ("7","Sat");
