#!/usr/bin/env ruby

require './app/env'
require './app/models'
require 'csv'

#"isect_st_full_nm" LIKE '%82ND AVE%' or "st_full_nm" LIKE '%82ND AVE%')
crashes = Crash.pedestrians.where("isect_st_full_nm LIKE '%82ND AVE%' or st_full_nm LIKE '%82ND AVE%'")
csv_out = CSV.generate do |csv|
  csv << [
    :date,
    :pedestrians,
    :cyclist,
    :movements,
    :errors,
    :injuries,
    :minor_injuries,
    :moderate_injuries,
    :major_injuries,
    :fatalities,
    :lat,
    :lon
  ]
  crashes.each do |crash|
    csv << [
      crash.crash_dt.to_date,
      crash.tot_ped_cnt,
      crash.tot_pedcycl_cnt,
      crash.vehicles.map(&:mvmnt_cd).join(' '),
      crash.errors.map(&:id).join(' '),
      crash.injuries,
      crash.minor_injuries,
      crash.moderate_injuries,
      crash.major_injuries,
      crash.fatalities,
      crash.lat,
      crash.lon
    ]
  end
end

puts csv_out
